insert into public.exercises (id,owner_id,name,muscle_group,equipment,type,is_custom,archived,updated_at)
select ('00000000-0000-4000-8000-' || lpad(ordinality::text,12,'0'))::uuid, null, name, muscle, equipment, kind, false, false, '2026-01-01T00:00:00Z'
from jsonb_to_recordset($catalog$[
 {"name":"Barbell Bench Press","muscle":"Chest","equipment":"Barbell","kind":"weighted"},
 {"name":"Incline Barbell Bench Press","muscle":"Chest","equipment":"Barbell","kind":"weighted"},
 {"name":"Dumbbell Bench Press","muscle":"Chest","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Incline Dumbbell Press","muscle":"Chest","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Chest Fly","muscle":"Chest","equipment":"Machine","kind":"weighted"},
 {"name":"Cable Crossover","muscle":"Chest","equipment":"Cable","kind":"weighted"},
 {"name":"Push-Up","muscle":"Chest","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Dip","muscle":"Chest","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Back Squat","muscle":"Quadriceps","equipment":"Barbell","kind":"weighted"},
 {"name":"Front Squat","muscle":"Quadriceps","equipment":"Barbell","kind":"weighted"},
 {"name":"Goblet Squat","muscle":"Quadriceps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Leg Press","muscle":"Quadriceps","equipment":"Machine","kind":"weighted"},
 {"name":"Leg Extension","muscle":"Quadriceps","equipment":"Machine","kind":"weighted"},
 {"name":"Bulgarian Split Squat","muscle":"Quadriceps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Walking Lunge","muscle":"Quadriceps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Step-Up","muscle":"Quadriceps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Deadlift","muscle":"Back","equipment":"Barbell","kind":"weighted"},
 {"name":"Romanian Deadlift","muscle":"Hamstrings","equipment":"Barbell","kind":"weighted"},
 {"name":"Sumo Deadlift","muscle":"Back","equipment":"Barbell","kind":"weighted"},
 {"name":"Hip Thrust","muscle":"Glutes","equipment":"Barbell","kind":"weighted"},
 {"name":"Leg Curl","muscle":"Hamstrings","equipment":"Machine","kind":"weighted"},
 {"name":"Good Morning","muscle":"Hamstrings","equipment":"Barbell","kind":"weighted"},
 {"name":"Glute Bridge","muscle":"Glutes","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Calf Raise","muscle":"Calves","equipment":"Machine","kind":"weighted"},
 {"name":"Pull-Up","muscle":"Back","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Chin-Up","muscle":"Back","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Lat Pulldown","muscle":"Back","equipment":"Cable","kind":"weighted"},
 {"name":"Barbell Row","muscle":"Back","equipment":"Barbell","kind":"weighted"},
 {"name":"Dumbbell Row","muscle":"Back","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Seated Cable Row","muscle":"Back","equipment":"Cable","kind":"weighted"},
 {"name":"Chest-Supported Row","muscle":"Back","equipment":"Machine","kind":"weighted"},
 {"name":"Face Pull","muscle":"Shoulders","equipment":"Cable","kind":"weighted"},
 {"name":"Overhead Press","muscle":"Shoulders","equipment":"Barbell","kind":"weighted"},
 {"name":"Dumbbell Shoulder Press","muscle":"Shoulders","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Arnold Press","muscle":"Shoulders","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Lateral Raise","muscle":"Shoulders","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Cable Lateral Raise","muscle":"Shoulders","equipment":"Cable","kind":"weighted"},
 {"name":"Rear Delt Fly","muscle":"Shoulders","equipment":"Machine","kind":"weighted"},
 {"name":"Upright Row","muscle":"Shoulders","equipment":"Barbell","kind":"weighted"},
 {"name":"Shrug","muscle":"Traps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Barbell Curl","muscle":"Biceps","equipment":"Barbell","kind":"weighted"},
 {"name":"Dumbbell Curl","muscle":"Biceps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Hammer Curl","muscle":"Biceps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Preacher Curl","muscle":"Biceps","equipment":"Machine","kind":"weighted"},
 {"name":"Cable Curl","muscle":"Biceps","equipment":"Cable","kind":"weighted"},
 {"name":"Concentration Curl","muscle":"Biceps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Triceps Pushdown","muscle":"Triceps","equipment":"Cable","kind":"weighted"},
 {"name":"Skull Crusher","muscle":"Triceps","equipment":"Barbell","kind":"weighted"},
 {"name":"Overhead Triceps Extension","muscle":"Triceps","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Close-Grip Bench Press","muscle":"Triceps","equipment":"Barbell","kind":"weighted"},
 {"name":"Bench Dip","muscle":"Triceps","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Diamond Push-Up","muscle":"Triceps","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Wrist Curl","muscle":"Forearms","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Reverse Curl","muscle":"Forearms","equipment":"Barbell","kind":"weighted"},
 {"name":"Plank","muscle":"Core","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Crunch","muscle":"Core","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Hanging Leg Raise","muscle":"Core","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Russian Twist","muscle":"Core","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Ab Wheel Rollout","muscle":"Core","equipment":"Other","kind":"bodyweight"},
 {"name":"Cable Crunch","muscle":"Core","equipment":"Cable","kind":"weighted"},
 {"name":"Mountain Climber","muscle":"Core","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Bicycle Crunch","muscle":"Core","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Bodyweight Squat","muscle":"Quadriceps","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Reverse Lunge","muscle":"Quadriceps","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Single-Leg Glute Bridge","muscle":"Glutes","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Nordic Curl","muscle":"Hamstrings","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Inverted Row","muscle":"Back","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Pike Push-Up","muscle":"Shoulders","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Burpee","muscle":"Full Body","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Muscle-Up","muscle":"Full Body","equipment":"Bodyweight","kind":"bodyweight"},
 {"name":"Kettlebell Swing","muscle":"Full Body","equipment":"Kettlebell","kind":"weighted"},
 {"name":"Kettlebell Goblet Squat","muscle":"Quadriceps","equipment":"Kettlebell","kind":"weighted"},
 {"name":"Farmer Carry","muscle":"Full Body","equipment":"Dumbbell","kind":"weighted"},
 {"name":"Clean and Press","muscle":"Full Body","equipment":"Barbell","kind":"weighted"},
 {"name":"Power Clean","muscle":"Full Body","equipment":"Barbell","kind":"weighted"},
 {"name":"Thruster","muscle":"Full Body","equipment":"Barbell","kind":"weighted"},
 {"name":"Landmine Press","muscle":"Shoulders","equipment":"Barbell","kind":"weighted"},
 {"name":"Hack Squat","muscle":"Quadriceps","equipment":"Machine","kind":"weighted"}
]$catalog$::jsonb) with ordinality as x(name text,muscle text,equipment text,kind text,ordinality bigint)
on conflict (id) do update set name=excluded.name,muscle_group=excluded.muscle_group,equipment=excluded.equipment,type=excluded.type,updated_at=excluded.updated_at;
