import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Card, EmptyState, Screen } from '../../src/components/ui';
import { CoachReviewListItem, listCoachReviews } from '../../src/data/database';
import { useTheme } from '../../src/theme';

export default function CoachArchive(){const t=useTheme();const router=useRouter();const [items,setItems]=useState<CoachReviewListItem[]>([]);useEffect(()=>{listCoachReviews(true).then(setItems).catch(console.warn)},[]);return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>router.back()} style={styles.icon}><Ionicons name="chevron-back" size={28} color={t.text}/></Pressable><Text style={[styles.title,{color:t.text}]}>Review archive</Text><View style={styles.icon}/></View>{!items.length?<EmptyState icon="📝" title="No reviews yet" body="Completed coach reviews will remain available here offline."/>:items.map(({record,archivedAt})=><Pressable accessibilityRole="button" key={record.id} onPress={()=>router.push(`/coach/review/${record.id}`)}><Card><View style={styles.row}><View style={{flex:1}}><Text style={[styles.status,{color:archivedAt?t.secondary:t.accentDark}]}>{archivedAt?'ARCHIVED':'AVAILABLE'}</Text><Text style={[styles.headline,{color:t.text}]}>{record.review.headline}</Text><Text style={{color:t.secondary}}>{record.review.periodStart}–{record.review.periodEnd}</Text></View><Ionicons name="chevron-forward" size={22} color={t.secondary}/></View></Card></Pressable>)}</ScrollView></Screen>}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:80,gap:12},header:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:6},icon:{width:48,height:48,alignItems:'center',justifyContent:'center'},title:{fontSize:25,fontWeight:'900'},row:{flexDirection:'row',alignItems:'center',gap:10},status:{fontSize:11,fontWeight:'900',letterSpacing:1.1,marginBottom:6},headline:{fontSize:17,fontWeight:'800',lineHeight:23,marginBottom:5}});
