import React, { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Card, PrimaryButton, Screen } from '../../../src/components/ui';
import { archiveCoachReview, CoachReviewListItem, getCoachReview, getCoachingContext, listCoachReviewFeedback, listCoachRoutineProposals, saveCoachReviewFeedback } from '../../../src/data/database';
import { CoachingContextV1 } from '../../../src/coaching/context';
import { reviewDataState } from '../../../src/coaching/reviews';
import { useApp } from '../../../src/context/AppContext';
import { useTheme } from '../../../src/theme';
import { CoachReviewFeedbackV1, CoachTone, CoachUsefulness } from '../../../src/coaching/feedback';
import { makeId } from '../../../src/data/id';
import { CoachRoutineProposalItem } from '../../../src/coaching/proposals';

export default function ReviewDetail(){const t=useTheme();const router=useRouter();const {id}=useLocalSearchParams<{id:string}>();const {refresh}=useApp();const [item,setItem]=useState<CoachReviewListItem|null>(null);const [context,setContext]=useState<CoachingContextV1|null>(null);const [proposal,setProposal]=useState<CoachRoutineProposalItem|null>(null);const [existingFeedback,setExistingFeedback]=useState<CoachReviewFeedbackV1|null>(null);const [usefulness,setUsefulness]=useState<CoachUsefulness>('helpful');const [tone,setTone]=useState<CoachTone>('right');const [changedConstraints,setChangedConstraints]=useState('');useEffect(()=>{Promise.all([getCoachReview(id),getCoachingContext(),listCoachReviewFeedback(),listCoachRoutineProposals(true)]).then(([review,nextContext,feedback,proposals])=>{setItem(review);setContext(nextContext);setProposal(proposals.find(value=>value.record.reviewId===id)??null);const existing=feedback.find(value=>value.reviewId===id)??null;setExistingFeedback(existing);if(existing){setUsefulness(existing.usefulness);setTone(existing.tone);setChangedConstraints(existing.changedConstraints??'')}}).catch(console.warn)},[id]);
  if(!item)return <Screen style={styles.center}><Text style={{color:t.secondary}}>Review not found.</Text></Screen>;
  const review=item.record.review;const archive=async()=>{await archiveCoachReview(item.record.id);refresh();router.back()};const saveFeedback=async()=>{const timestamp=new Date().toISOString();const feedback:CoachReviewFeedbackV1={feedbackVersion:1,id:existingFeedback?.id??makeId(),reviewId:item.record.id,profileId:item.record.profileId,profileRevision:item.record.profileRevision,usefulness,tone,changedConstraints:changedConstraints.trim()||null,createdAt:existingFeedback?.createdAt??timestamp,updatedAt:timestamp};try{await saveCoachReviewFeedback(feedback);setExistingFeedback(feedback);refresh();Alert.alert('Feedback saved','Coach will receive it in the next review context.')}catch(error){Alert.alert('Could not save feedback',error instanceof Error?error.message:String(error))}};
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>router.back()} style={styles.icon}><Ionicons name="chevron-back" size={28} color={t.text}/></Pressable><Text style={[styles.title,{color:t.text}]}>Review</Text><View style={styles.icon}/></View>
    {reviewDataState(item.record,context)==='superseded'&&<Card style={{borderColor:t.danger}}><Text style={[styles.label,{color:t.danger}]}>DATA CHANGED</Text><Text style={[styles.body,{color:t.text}]}>Workout history or goals used by this review have changed. The review remains an immutable snapshot; request an updated review for current guidance.</Text></Card>}
    <Text style={[styles.period,{color:t.secondary}]}>{review.periodStart}–{review.periodEnd} · {review.authoredBy}</Text><Text style={[styles.headline,{color:t.text}]}>{review.headline}</Text>
    {review.journeyHighlight&&<Card><Text style={[styles.label,{color:t.accentDark}]}>JOURNEY HIGHLIGHT</Text><Text style={[styles.sectionTitle,{color:t.text}]}>{review.journeyHighlight.text}</Text><Evidence ids={review.journeyHighlight.evidenceWorkoutIds}/></Card>}
    <Text style={[styles.heading,{color:t.text}]}>What the record shows</Text>{review.observations.map((observation,index)=><Card key={`${observation.category}-${index}`}><Text style={[styles.label,{color:t.accentDark}]}>{observation.category.toUpperCase()}</Text><Text style={[styles.body,{color:t.text}]}>{observation.text}</Text><Evidence ids={observation.evidenceWorkoutIds}/></Card>)}
    <Card style={{backgroundColor:t.elevated}}><Text style={[styles.label,{color:t.secondary}]}>NEXT ACHIEVABLE STEP</Text><Text style={[styles.sectionTitle,{color:t.text}]}>{review.nextStep.title}</Text><Text style={[styles.body,{color:t.secondary}]}>{review.nextStep.rationale}</Text></Card>
    {proposal&&<Card style={{borderColor:t.accentDark}}><Text style={[styles.label,{color:t.accentDark}]}>ROUTINE RECOMMENDATION · {proposal.status.toUpperCase()}</Text><Text style={[styles.sectionTitle,{color:t.text}]}>{proposal.record.proposal.name}</Text><Text style={[styles.body,{color:t.secondary}]}>{proposal.record.proposal.summary}</Text><View style={{marginTop:12}}><PrimaryButton title="Compare routine" kind="secondary" onPress={()=>router.push(`/coach/proposal/${proposal.record.id}`)}/></View></Card>}
    <Text style={[styles.heading,{color:t.text}]}>Confidence & context</Text><Card><Text style={[styles.body,{color:t.text}]}>{review.confidence[0].toUpperCase()+review.confidence.slice(1)} confidence</Text>{review.limitations.map((value)=><Text key={value} style={[styles.bullet,{color:t.secondary}]}>• {value}</Text>)}{review.contextUsed.map((source)=><View key={`${source.source}-${source.label}`} style={styles.source}><Text style={[styles.body,{color:t.text}]}>{source.label}</Text><Text style={[styles.small,{color:t.secondary}]}>{source.status} · {source.startDate??'date unavailable'}–{source.endDate??'date unavailable'}</Text></View>)}</Card>
    <Text style={[styles.heading,{color:t.text}]}>Help Coach adapt</Text><Card><Text style={[styles.label,{color:t.secondary}]}>WAS THIS USEFUL?</Text><ChoiceRow values={[['helpful','Helpful'],['not_helpful','Not helpful']]} selected={usefulness} onSelect={(value)=>setUsefulness(value as CoachUsefulness)}/><Text style={[styles.label,{color:t.secondary,marginTop:16}]}>TONE</Text><ChoiceRow values={[['too_gentle','Too gentle'],['right','Right'],['too_direct','Too direct']]} selected={tone} onSelect={(value)=>setTone(value as CoachTone)}/><Text style={[styles.label,{color:t.secondary,marginTop:16}]}>WHAT CHANGED? (OPTIONAL)</Text><TextInput accessibilityLabel="Changed training constraints" value={changedConstraints} onChangeText={setChangedConstraints} multiline placeholder="Availability, recovery, or another constraint" placeholderTextColor={t.secondary} style={[styles.input,{color:t.text,backgroundColor:t.input}]}/><View style={{marginTop:12}}><PrimaryButton title={existingFeedback?'Update feedback':'Save feedback'} onPress={saveFeedback}/></View></Card>
    {!item.archivedAt&&<PrimaryButton kind="secondary" title="Archive review" onPress={()=>Alert.alert('Archive review?','You can still find it in the review archive.',[{text:'Cancel',style:'cancel'},{text:'Archive',onPress:archive}])}/>} 
  </ScrollView></Screen>;
}

function Evidence({ids}:{ids:string[]}){const t=useTheme();const router=useRouter();if(!ids.length)return null;return <View style={styles.evidence}>{ids.map(id=><Pressable accessibilityRole="link" key={id} onPress={()=>router.push(`/history/${id}`)} style={[styles.evidenceButton,{backgroundColor:t.elevated}]}><Ionicons name="document-text-outline" size={16} color={t.accentDark}/><Text style={{color:t.accentDark,fontWeight:'700'}}>View workout</Text></Pressable>)}</View>}
function ChoiceRow({values,selected,onSelect}:{values:string[][];selected:string;onSelect:(value:string)=>void}){const t=useTheme();return <View style={styles.choices}>{values.map(([value,label])=><Pressable accessibilityRole="radio" accessibilityState={{checked:selected===value}} key={value} onPress={()=>onSelect(value)} style={[styles.choice,{backgroundColor:selected===value?t.accent:t.elevated}]}><Text style={{color:selected===value?'#07150C':t.text,fontWeight:'700'}}>{label}</Text></Pressable>)}</View>}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:80,gap:13},center:{alignItems:'center',justifyContent:'center'},header:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},icon:{width:48,height:48,alignItems:'center',justifyContent:'center'},title:{fontSize:25,fontWeight:'900'},period:{fontSize:13,textAlign:'center'},headline:{fontSize:28,fontWeight:'900',lineHeight:35,marginVertical:6},label:{fontSize:11,fontWeight:'900',letterSpacing:1.1,marginBottom:7},heading:{fontSize:20,fontWeight:'800',marginTop:10},sectionTitle:{fontSize:18,fontWeight:'800',lineHeight:25,marginBottom:6},body:{fontSize:15,lineHeight:22},small:{fontSize:12,lineHeight:18},bullet:{fontSize:14,lineHeight:21,marginTop:7},source:{marginTop:13},evidence:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},evidenceButton:{minHeight:44,borderRadius:22,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:6},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},choice:{minHeight:44,borderRadius:22,paddingHorizontal:13,alignItems:'center',justifyContent:'center'},input:{minHeight:84,borderRadius:12,padding:12,fontSize:15,textAlignVertical:'top'}});
