import React, { useEffect, useState } from 'react';
import { Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { ExercisePicker } from '../src/components/ExercisePicker';
import { Card, EmptyState, PrimaryButton, Screen } from '../src/components/ui';
import { addExerciseToWorkout, addSet, discardWorkout, finishWorkout, getActiveWorkout, moveWorkoutExercise, removeSet, removeWorkoutExercise, toggleSet, updateSet } from '../src/data/database';
import { useApp } from '../src/context/AppContext';
import { useTheme } from '../src/theme';
import { WorkoutExercise, WorkoutSet } from '../src/types';
import { secondsToClock, validReps, validWeight, workoutDuration } from '../src/utils';
import { canCompleteSet, previousLabel } from '../src/domain';

function SetRow({set,type,onChanged,onComplete}:{set:WorkoutSet;type:'weighted'|'bodyweight';onChanged:()=>void;onComplete:()=>void}){const t=useTheme();const [weight,setWeight]=useState(set.weight?.toString()??'');const [reps,setReps]=useState(set.reps?.toString()??'');
  useEffect(()=>{setWeight(set.weight?.toString()??'');setReps(set.reps?.toString()??'')},[set.weight,set.reps]);
  const finish=async()=>{const repValue=reps===''?null:Number(reps);const weightValue=weight===''?null:Number(weight);if(!canCompleteSet(type,weightValue,repValue))return Alert.alert(type==='weighted'?'Enter weight and reps first':'Enter reps first');await updateSet(set.id,'reps',repValue);if(type==='weighted')await updateSet(set.id,'weight',weightValue);const completed=await toggleSet(set.id);if(completed)onComplete();onChanged()};
  const previous=previousLabel(set.previous);
  return <View style={[styles.setRow,set.completedAt&&{opacity:.58}]}><Text style={[styles.setNumber,{color:t.secondary}]}>{set.setNumber}</Text><Text style={[styles.previous,{color:t.secondary}]}>{previous}</Text>{type==='weighted'&&<TextInput accessibilityLabel={`Set ${set.setNumber} weight`} editable={!set.completedAt} selectTextOnFocus keyboardType="decimal-pad" value={weight} onChangeText={v=>validWeight(v)&&setWeight(v)} onBlur={()=>updateSet(set.id,'weight',weight===''?null:Number(weight))} placeholder="0" placeholderTextColor={t.secondary} style={[styles.numberInput,{color:t.text,backgroundColor:t.input}]}/>}<TextInput accessibilityLabel={`Set ${set.setNumber} reps`} editable={!set.completedAt} selectTextOnFocus keyboardType="number-pad" value={reps} onChangeText={v=>validReps(v)&&setReps(v)} onBlur={()=>updateSet(set.id,'reps',reps===''?null:Number(reps))} placeholder="0" placeholderTextColor={t.secondary} style={[styles.numberInput,{color:t.text,backgroundColor:t.input}]}/><Pressable accessibilityLabel={set.completedAt?'Mark set incomplete':'Complete set'} onPress={finish} style={[styles.check,{backgroundColor:set.completedAt?t.accent:t.elevated}]}><Ionicons name="checkmark" size={22} color={set.completedAt?'#07150C':t.secondary}/></Pressable>{!set.completedAt&&<Pressable accessibilityLabel="Remove set" hitSlop={8} onPress={async()=>{await removeSet(set.id);onChanged()}}><Ionicons name="close" size={18} color={t.secondary}/></Pressable>}</View>;
}

function ExerciseCard({exercise,index,total,onChanged,onComplete}:{exercise:WorkoutExercise;index:number;total:number;onChanged:()=>void;onComplete:()=>void}){const t=useTheme();const remove=()=>Alert.alert(`Remove ${exercise.exerciseName}?`,'Any sets logged for this exercise will be deleted.',[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:async()=>{await removeWorkoutExercise(exercise.id);onChanged()}}]);return <Card style={styles.exerciseCard}><View style={styles.exerciseHeader}><View style={{flex:1}}><Text style={[styles.exerciseName,{color:t.text}]}>{exercise.exerciseName}</Text><Text style={{color:t.secondary}}>{exercise.exerciseType==='bodyweight'?'Bodyweight':'Weighted'}</Text></View><View style={styles.exerciseActions}><Pressable disabled={index===0} onPress={async()=>{await moveWorkoutExercise(exercise.id,-1);onChanged()}}><Ionicons name="arrow-up" size={20} color={index===0?t.border:t.secondary}/></Pressable><Pressable disabled={index===total-1} onPress={async()=>{await moveWorkoutExercise(exercise.id,1);onChanged()}}><Ionicons name="arrow-down" size={20} color={index===total-1?t.border:t.secondary}/></Pressable><Pressable onPress={remove}><Ionicons name="trash-outline" size={20} color={t.danger}/></Pressable></View></View><View style={styles.columns}><Text style={[styles.colSet,{color:t.secondary}]}>SET</Text><Text style={[styles.colPrevious,{color:t.secondary}]}>PREVIOUS</Text>{exercise.exerciseType==='weighted'&&<Text style={[styles.colNumber,{color:t.secondary}]}>WEIGHT</Text>}<Text style={[styles.colNumber,{color:t.secondary}]}>REPS</Text><View style={{width:58}}/></View>{exercise.sets.map(set=><SetRow key={set.id} set={set} type={exercise.exerciseType} onChanged={onChanged} onComplete={onComplete}/>)}<Pressable onPress={async()=>{await addSet(exercise.id);onChanged()}} style={[styles.addSet,{backgroundColor:t.elevated}]}><Ionicons name="add" size={18} color={t.accentDark}/><Text style={{color:t.accentDark,fontWeight:'800'}}>Add set</Text></Pressable></Card>}

function TimerBanner(){const t=useTheme();const {timerEnd,cancelTimer}=useApp();const [,tick]=useState(0);useEffect(()=>{if(!timerEnd)return;const id=setInterval(()=>tick(v=>v+1),500);return()=>clearInterval(id)},[timerEnd]);if(!timerEnd)return null;const remaining=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));return <View style={[styles.timer,{backgroundColor:t.accent}]}><Ionicons name="timer-outline" size={21} color="#07150C"/><Text style={styles.timerText}>{remaining?`Rest ${secondsToClock(remaining)}`:'Rest complete'}</Text><Pressable onPress={cancelTimer}><Text style={styles.timerSkip}>{remaining?'Skip':'Dismiss'}</Text></Pressable></View>}

export default function ActiveWorkout(){const t=useTheme();const router=useRouter();const {refresh,startTimer,cancelTimer}=useApp();const [workout,setWorkout]=useState<Awaited<ReturnType<typeof getActiveWorkout>>>(null);const [picker,setPicker]=useState(false);const [stamp,setStamp]=useState(0);useEffect(()=>{getActiveWorkout().then(setWorkout)},[stamp]);const changed=()=>{setStamp(v=>v+1);refresh()};
  if(!workout)return <Screen><EmptyState icon="✓" title="No active workout" body="Start one from the Workout tab."/><View style={{padding:20}}><PrimaryButton title="Done" onPress={()=>router.replace('/')} /></View></Screen>;
  const finish=async()=>{try{await finishWorkout(workout.id);await cancelTimer();changed();router.replace('/history')}catch(e){Alert.alert('Not finished',e instanceof Error?e.message:String(e))}};
  const discard=()=>Alert.alert('Discard workout?','This active workout and its sets will be permanently removed.',[{text:'Keep workout',style:'cancel'},{text:'Discard',style:'destructive',onPress:async()=>{await discardWorkout(workout.id);await cancelTimer();changed();router.replace('/')}}]);
  return <Screen><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.top}><Pressable accessibilityLabel="Close workout" onPress={()=>router.back()} style={styles.headerAction}><Ionicons name="chevron-down" size={28} color={t.text}/></Pressable><View style={styles.workoutTitle}><Text numberOfLines={1} style={[styles.workoutName,{color:t.text}]}>{workout.name}</Text><Text style={{color:t.secondary}}>{workoutDuration(workout.startedAt)}</Text></View><Pressable testID="finish-workout" accessibilityRole="button" accessibilityLabel="Finish workout" onPress={finish} style={styles.headerAction}><Text style={[styles.finish,{color:t.accentDark}]}>Finish</Text></Pressable></View><TimerBanner/><FlatList data={workout.exercises} keyExtractor={e=>e.id} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" ListEmptyComponent={<EmptyState icon="＋" title="Add your first exercise" body="Build this workout as you go."/>} renderItem={({item,index})=><ExerciseCard exercise={item} index={index} total={workout.exercises.length} onChanged={changed} onComplete={startTimer}/>} ListFooterComponent={<View style={{gap:12}}><PrimaryButton title="Add exercise" kind="secondary" onPress={()=>setPicker(true)}/><PrimaryButton title="Finish workout" onPress={finish}/><PrimaryButton title="Discard workout" kind="danger" onPress={discard}/></View>}/><ExercisePicker visible={picker} onClose={()=>setPicker(false)} onSelect={async exercise=>{await addExerciseToWorkout(workout.id,exercise.id);setPicker(false);changed()}}/></KeyboardAvoidingView></Screen>;
}
const styles=StyleSheet.create({top:{height:62,paddingHorizontal:8,flexDirection:'row',alignItems:'center'},headerAction:{width:72,minHeight:44,alignItems:'center',justifyContent:'center'},workoutTitle:{flex:1,minWidth:0,alignItems:'center'},workoutName:{fontSize:17,fontWeight:'800',maxWidth:'100%'},finish:{fontSize:16,fontWeight:'900'},content:{padding:14,paddingBottom:50,gap:12},exerciseCard:{padding:14},exerciseHeader:{flexDirection:'row',alignItems:'center',marginBottom:16},exerciseName:{fontSize:18,fontWeight:'800',marginBottom:3},exerciseActions:{flexDirection:'row',gap:16},columns:{flexDirection:'row',alignItems:'center',marginBottom:6},columnsText:{fontSize:10,fontWeight:'800'},colSet:{width:30,fontSize:10,fontWeight:'800'},colPrevious:{flex:1,fontSize:10,fontWeight:'800'},colNumber:{width:66,textAlign:'center',fontSize:10,fontWeight:'800'},setRow:{minHeight:48,flexDirection:'row',alignItems:'center',gap:6},setNumber:{width:24,textAlign:'center',fontWeight:'800'},previous:{flex:1,fontSize:12},numberInput:{width:66,height:40,borderRadius:10,textAlign:'center',fontSize:16,fontWeight:'700'},check:{width:40,height:40,borderRadius:11,alignItems:'center',justifyContent:'center'},addSet:{height:42,borderRadius:11,marginTop:8,flexDirection:'row',gap:5,alignItems:'center',justifyContent:'center'},timer:{marginHorizontal:14,borderRadius:13,height:48,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:8},timerText:{color:'#07150C',fontSize:16,fontWeight:'900',flex:1},timerSkip:{color:'#07150C',fontWeight:'800'}});
