import React, { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Card, PrimaryButton, Screen } from '../../src/components/ui';
import { useApp } from '../../src/context/AppContext';
import { CoachReviewListItem, getCoachingContext, getCurrentCoachingProfile, listCoachReviews, listCoachingGenerationRequests, listCoachRoutineProposals, requestCoachReview, retryCoachingGenerationRequest } from '../../src/data/database';
import { CoachingProfileV1 } from '../../src/coaching/goals';
import { CoachingContextV1 } from '../../src/coaching/context';
import { CoachingGenerationRequestV1 } from '../../src/coaching/workflow';
import { reviewDataState } from '../../src/coaching/reviews';
import { CoachRoutineProposalItem } from '../../src/coaching/proposals';
import { useTheme } from '../../src/theme';

export default function CoachScreen() {
  const t=useTheme(); const router=useRouter(); const { revision, refresh, syncNow, session }=useApp();
  const [profile,setProfile]=useState<CoachingProfileV1|null>(null); const [context,setContext]=useState<CoachingContextV1|null>(null);
  const [reviews,setReviews]=useState<CoachReviewListItem[]>([]); const [requests,setRequests]=useState<CoachingGenerationRequestV1[]>([]); const [proposals,setProposals]=useState<CoachRoutineProposalItem[]>([]); const [working,setWorking]=useState(false);
  const load=useCallback(async()=>{const [nextProfile,nextReviews,nextRequests,nextContext,nextProposals]=await Promise.all([getCurrentCoachingProfile(),listCoachReviews(),listCoachingGenerationRequests(),getCoachingContext(),listCoachRoutineProposals()]);setProfile(nextProfile);setReviews(nextReviews);setRequests(nextRequests);setContext(nextContext);setProposals(nextProposals)},[]);
  useEffect(()=>{load().catch(console.warn)},[load,revision]);
  const request=async()=>{setWorking(true);try{await requestCoachReview();refresh();if(session)await syncNow();await load()}catch(error){Alert.alert('Could not request review',error instanceof Error?error.message:String(error))}finally{setWorking(false)}};
  const retry=async(id:string)=>{setWorking(true);try{await retryCoachingGenerationRequest(id);refresh();if(session)await syncNow();await load()}catch(error){Alert.alert('Could not retry',error instanceof Error?error.message:String(error))}finally{setWorking(false)}};
  const latest=reviews[0]?.record??null; const latestState=latest?reviewDataState(latest,context):null; const activeRequest=requests.find(item=>item.generationKey===context?.generationKey)??requests[0]??null;
  const state=activeRequest?.status; const delayed=state==='pending'&&activeRequest.nextAttemptAt&&new Date(activeRequest.nextAttemptAt)>new Date();
  return <Screen><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.heading}><View><Text style={[styles.eyebrow,{color:t.accentDark}]}>WEEKLY REVIEW</Text><Text style={[styles.title,{color:t.text}]}>Coach</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Open coach settings" onPress={()=>router.push('/coach/goals')} style={[styles.icon,{backgroundColor:t.elevated}]}><Ionicons name="options-outline" size={24} color={t.text}/></Pressable></View>
    {!profile?<Card><Text style={[styles.cardTitle,{color:t.text}]}>Set your direction</Text><Text style={[styles.body,{color:t.secondary}]}>Choose a primary goal and minimum training constraints before Coach reviews your history.</Text><View style={styles.buttonGap}><PrimaryButton title="Set my goals" onPress={()=>router.push('/coach/goals')}/></View></Card>:!profile.consent.coachingEnabled||!profile.consent.shareWorkoutHistory?<Card><Text style={[styles.cardTitle,{color:t.text}]}>Coach is off</Text><Text style={[styles.body,{color:t.secondary}]}>Your workout history stays private until you explicitly enable Coach and history access.</Text><View style={styles.buttonGap}><PrimaryButton title="Review privacy settings" onPress={()=>router.push('/coach/goals')}/></View></Card>:<>
      <Card><View style={styles.cardHeader}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:t.text}]}>Training data available</Text><Text style={[styles.body,{color:t.secondary}]}>{context?.metrics.coverage.totalCompletedWorkouts??0} completed workouts · {context?.metrics.period.startDate}–{context?.metrics.period.endDate}</Text></View><Ionicons name="shield-checkmark-outline" size={26} color={t.accentDark}/></View><Text style={[styles.small,{color:t.secondary}]}>Incomplete sets are excluded. Loads are normalized before per-exercise comparisons.</Text></Card>
      {proposals.map(({record})=><Pressable key={record.id} accessibilityRole="button" accessibilityLabel={`Review routine recommendation: ${record.proposal.name}`} onPress={()=>router.push(`/coach/proposal/${record.id}`)}><Card style={{borderColor:t.accentDark}}><View style={styles.cardHeader}><Text style={[styles.status,{color:t.accentDark}]}>ROUTINE RECOMMENDATION</Text><Ionicons name="chevron-forward" size={22} color={t.secondary}/></View><Text style={[styles.reviewTitle,{color:t.text}]}>{record.proposal.name}</Text><Text style={[styles.body,{color:t.secondary}]}>{record.proposal.summary}</Text><Text style={[styles.small,{color:t.accentDark,marginTop:12,fontWeight:'800'}]}>Preview and accept or decline</Text></Card></Pressable>)}
      {activeRequest&&state!=='ready'?<Card><Text style={[styles.status,{color:state==='failed'?t.danger:t.accentDark}]}>{state==='processing'?'COACH IS REVIEWING':state==='failed'?'REVIEW FAILED':delayed?'RETRY SCHEDULED':'WAITING FOR COACH'}</Text><Text style={[styles.cardTitle,{color:t.text}]}>{state==='failed'?'Your workouts are safe':'Your review is being prepared'}</Text><Text style={[styles.body,{color:t.secondary}]}>{state==='failed'?(activeRequest.lastError??'The agent could not finish this review.'):delayed?`Next retry after ${new Date(activeRequest.nextAttemptAt!).toLocaleString()}`:session?'You can keep logging workouts while this runs.':'Sign in to sync this request to your coach.'}</Text>{state==='failed'&&<View style={styles.buttonGap}><PrimaryButton disabled={working} title="Retry review" onPress={()=>retry(activeRequest.id)}/></View>}</Card>:null}
      {latest?<Pressable accessibilityRole="button" accessibilityLabel={`Open coach review: ${latest.review.headline}`} onPress={()=>router.push(`/coach/review/${latest.id}`)}><Card><View style={styles.cardHeader}><Text style={[styles.status,{color:t.accentDark}]}>{latestState==='superseded'?'BASED ON EARLIER DATA':'LATEST REVIEW'}</Text><Ionicons name="chevron-forward" size={22} color={t.secondary}/></View><Text style={[styles.reviewTitle,{color:t.text}]}>{latest.review.headline}</Text><Text style={[styles.body,{color:t.secondary}]}>{latest.review.periodStart}–{latest.review.periodEnd} · {latest.review.confidence} confidence</Text><View style={[styles.next,{backgroundColor:t.elevated}]}><Text style={[styles.small,{color:t.secondary}]}>NEXT STEP</Text><Text style={[styles.nextTitle,{color:t.text}]}>{latest.review.nextStep.title}</Text></View></Card></Pressable>:<Card><Text style={[styles.cardTitle,{color:t.text}]}>Your first review</Text><Text style={[styles.body,{color:t.secondary}]}>Coach will use the completed local week, your current goal, and only the evidence shown above.</Text><View style={styles.buttonGap}><PrimaryButton disabled={working||state==='pending'||state==='processing'} title={working?'Requesting…':'Request weekly review'} onPress={request}/></View></Card>}
      {latestState==='superseded'&&(!activeRequest||activeRequest.generationKey!==context?.generationKey||state==='failed')&&<PrimaryButton kind="secondary" disabled={working} title="Request updated review" onPress={request}/>} 
      <Pressable accessibilityRole="button" onPress={()=>router.push('/coach/archive')} style={styles.archive}><Text style={{color:t.accentDark,fontWeight:'800'}}>Review archive</Text><Ionicons name="arrow-forward" size={20} color={t.accentDark}/></Pressable>
    </>}
  </ScrollView></Screen>;
}

const styles=StyleSheet.create({content:{padding:20,paddingBottom:120,gap:14},heading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.4},title:{fontSize:32,fontWeight:'900'},icon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},cardHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},cardTitle:{fontSize:19,fontWeight:'800',marginBottom:6},reviewTitle:{fontSize:21,fontWeight:'800',lineHeight:28,marginVertical:8},body:{fontSize:14,lineHeight:21},small:{fontSize:12,lineHeight:18},status:{fontSize:11,fontWeight:'900',letterSpacing:1.1,marginBottom:7},buttonGap:{marginTop:16},next:{marginTop:14,borderRadius:12,padding:12},nextTitle:{fontSize:16,fontWeight:'800',marginTop:3},archive:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8}});
