import React, { useEffect, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Card, EmptyState, PrimaryButton, Screen } from '../../src/components/ui';
import { createWorkout, listHistory, listRoutines } from '../../src/data/database';
import { useApp } from '../../src/context/AppContext';
import { Routine, WorkoutSession } from '../../src/types';
import { useTheme } from '../../src/theme';
import { workoutDuration } from '../../src/utils';

export default function WorkoutHome(){const t=useTheme();const router=useRouter();const {revision,activeWorkout,refresh}=useApp();const [routines,setRoutines]=useState<Routine[]>([]);const [recent,setRecent]=useState<WorkoutSession[]>([]);
  useEffect(()=>{listRoutines().then(setRoutines);listHistory().then(v=>setRecent(v.slice(0,3)));},[revision]);
  const start=async(routineId:string|null)=>{await createWorkout(routineId);refresh();router.push('/workout');};
  return <Screen><FlatList data={routines.slice(0,4)} keyExtractor={i=>i.id} contentContainerStyle={styles.content} ListHeaderComponent={<>
    <View style={styles.heading}><View><Text style={[styles.eyebrow,{color:t.accentDark}]}>WORKOUTPAL</Text><Text style={[styles.title,{color:t.text}]}>Ready to train?</Text></View><View style={[styles.logo,{backgroundColor:t.accent}]}><Ionicons name="barbell" size={23} color="#07150C"/></View></View>
    {activeWorkout?<Card style={styles.active}><View style={{flex:1}}><Text style={[styles.activeLabel,{color:t.accentDark}]}>WORKOUT IN PROGRESS</Text><Text style={[styles.activeTitle,{color:t.text}]}>{activeWorkout.name}</Text><Text style={{color:t.secondary}}>{workoutDuration(activeWorkout.startedAt)} · {activeWorkout.exercises.length} exercises</Text></View><Pressable onPress={()=>router.push('/workout')} style={[styles.resume,{backgroundColor:t.accent}]}><Ionicons name="arrow-forward" size={24} color="#07150C"/></Pressable></Card>:<PrimaryButton title="Start an empty workout" onPress={()=>start(null)}/>} 
    <View style={styles.sectionHead}><Text style={[styles.sectionTitle,{color:t.text}]}>Quick start</Text><Pressable onPress={()=>router.push('/routines')}><Text style={{color:t.accentDark,fontWeight:'700'}}>See all</Text></Pressable></View>
    {!routines.length&&<EmptyState icon="🏋️" title="No routines yet" body="Build your first routine, or start an empty workout."/>}
  </>} renderItem={({item})=><Pressable onPress={()=>start(item.id)}><Card style={styles.routine}><View style={{flex:1}}><Text style={[styles.routineName,{color:t.text}]}>{item.name}</Text><Text numberOfLines={1} style={{color:t.secondary}}>{item.exercises.map(e=>e.exercise?.name).join(' · ')}</Text></View><Ionicons name="play-circle" size={34} color={t.accent}/></Card></Pressable>} ListFooterComponent={<View><Text style={[styles.sectionTitle,{color:t.text,marginTop:26,marginBottom:12}]}>Recent</Text>{recent.length?recent.map(item=><Pressable key={item.id} onPress={()=>router.push(`/history/${item.id}`)}><View style={[styles.history,{borderBottomColor:t.border}]}><View><Text style={[styles.historyName,{color:t.text}]}>{item.name}</Text><Text style={{color:t.secondary}}>{new Date(item.endedAt!).toLocaleDateString()} · {workoutDuration(item.startedAt,item.endedAt)}</Text></View><Text style={[styles.setCount,{color:t.text}]}>{item.exercises.reduce((n,e)=>n+e.sets.length,0)} sets</Text></View></Pressable>):<Text style={{color:t.secondary}}>Completed workouts will appear here.</Text>}</View>}/></Screen>;
}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:120},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:24},eyebrow:{fontSize:12,fontWeight:'900',letterSpacing:1.5},title:{fontSize:30,fontWeight:'900',letterSpacing:-.8,marginTop:4},logo:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},active:{flexDirection:'row',alignItems:'center',marginBottom:20},activeLabel:{fontSize:11,fontWeight:'900'},activeTitle:{fontSize:20,fontWeight:'800',marginVertical:4},resume:{width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center'},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:28,marginBottom:12},sectionTitle:{fontSize:20,fontWeight:'800'},routine:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:10},routineName:{fontSize:17,fontWeight:'800',marginBottom:5},history:{paddingVertical:15,borderBottomWidth:1,flexDirection:'row',justifyContent:'space-between'},historyName:{fontSize:16,fontWeight:'700',marginBottom:4},setCount:{fontWeight:'700'}});
