import React, { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Card, PrimaryButton, Screen } from '../../src/components/ui';
import { savePreferences } from '../../src/data/database';
import { isSupabaseConfigured, sendMagicLink, supabase } from '../../src/data/supabase';
import { useApp } from '../../src/context/AppContext';
import { WeightUnit } from '../../src/types';
import { useTheme } from '../../src/theme';

export default function Settings(){const t=useTheme();const {preferences,session,syncStatus,syncNow,refresh}=useApp();const [unit,setUnit]=useState<WeightUnit>(preferences.unit);const [rest,setRest]=useState(String(preferences.restSeconds));const [email,setEmail]=useState('');const [sending,setSending]=useState(false);useEffect(()=>{setUnit(preferences.unit);setRest(String(preferences.restSeconds))},[preferences]);
  const save=async(nextUnit=unit,nextRest=rest)=>{const seconds=Math.min(600,Math.max(15,Number(nextRest)||90));setRest(String(seconds));await savePreferences({unit:nextUnit,restSeconds:seconds});refresh()};
  const login=async()=>{if(!email.includes('@'))return Alert.alert('Enter a valid email');setSending(true);try{await sendMagicLink(email);Alert.alert('Check your email','Tap the WorkoutPal sign-in link on this phone.')}catch(e){Alert.alert('Could not send link',e instanceof Error?e.message:String(e))}finally{setSending(false)}};
  return <Screen><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={[styles.title,{color:t.text}]}>Settings</Text><Text style={[styles.section,{color:t.secondary}]}>TRAINING</Text><Card><Text style={[styles.label,{color:t.text}]}>Weight unit</Text><View style={styles.segment}>{(['lb','kg'] as WeightUnit[]).map(value=><Pressable key={value} onPress={()=>{setUnit(value);save(value,rest)}} style={[styles.segmentButton,{backgroundColor:unit===value?t.accent:t.elevated}]}><Text style={{color:unit===value?'#07150C':t.text,fontSize:16,fontWeight:'800'}}>{value}</Text></Pressable>)}</View><View style={[styles.divider,{backgroundColor:t.border}]}/><Text style={[styles.label,{color:t.text}]}>Rest timer</Text><View style={styles.restRow}><TextInput value={rest} onChangeText={setRest} onBlur={()=>save()} keyboardType="number-pad" style={[styles.restInput,{backgroundColor:t.input,color:t.text}]}/><Text style={{color:t.secondary}}>seconds</Text></View></Card><Text style={[styles.section,{color:t.secondary}]}>SYNC</Text><Card><View style={styles.syncRow}><View style={[styles.statusDot,{backgroundColor:syncStatus==='idle'?t.accent:syncStatus==='error'?t.danger:t.secondary}]}/><View style={{flex:1}}><Text style={[styles.label,{color:t.text}]}>{session?'Supabase connected':'Local mode'}</Text><Text style={{color:t.secondary,marginTop:3}}>{session?session.user.email:!isSupabaseConfigured?'Add credentials in .env to enable sync.':'Sign in to back up your workouts.'}</Text></View>{session&&<Pressable onPress={syncNow}><Ionicons name="sync" size={23} color={t.accentDark}/></Pressable>}</View>{session?<><View style={[styles.divider,{backgroundColor:t.border}]}/><PrimaryButton title="Sign out" kind="secondary" onPress={()=>supabase?.auth.signOut()}/></>:isSupabaseConfigured?<View style={{gap:12,marginTop:16}}><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" textContentType="emailAddress" placeholder="you@example.com" placeholderTextColor={t.secondary} style={[styles.email,{backgroundColor:t.input,color:t.text}]}/><PrimaryButton disabled={sending} title={sending?'Sending…':'Email me a sign-in link'} onPress={login}/></View>:null}</Card><Text style={[styles.foot,{color:t.secondary}]}>WorkoutPal keeps logging available offline. Sync retries automatically when you reconnect.</Text></ScrollView></Screen>}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:120},title:{fontSize:32,fontWeight:'900',marginBottom:24},section:{fontSize:12,fontWeight:'900',letterSpacing:1.2,marginTop:18,marginBottom:8},label:{fontSize:16,fontWeight:'700'},segment:{flexDirection:'row',gap:8,marginTop:12},segmentButton:{flex:1,height:43,borderRadius:11,alignItems:'center',justifyContent:'center'},divider:{height:1,marginVertical:17},restRow:{flexDirection:'row',alignItems:'center',gap:10,marginTop:10},restInput:{width:90,height:44,borderRadius:11,textAlign:'center',fontSize:17,fontWeight:'700'},syncRow:{flexDirection:'row',alignItems:'center',gap:11},statusDot:{width:10,height:10,borderRadius:5},email:{height:50,borderRadius:12,paddingHorizontal:14,fontSize:16},foot:{fontSize:13,lineHeight:19,textAlign:'center',marginTop:18}});
