import React, { useEffect, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { ExercisePicker } from '../../src/components/ExercisePicker';
import { PrimaryButton, Screen } from '../../src/components/ui';
import { getRoutine, saveRoutine } from '../../src/data/database';
import { Exercise } from '../../src/types';
import { useApp } from '../../src/context/AppContext';
import { useTheme } from '../../src/theme';

type Draft={exercise:Exercise;setCount:number};
export default function RoutineEditor(){const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const t=useTheme();const {refresh}=useApp();const [name,setName]=useState('');const [items,setItems]=useState<Draft[]>([]);const [picker,setPicker]=useState(false);
  useEffect(()=>{if(id&&id!=='new')getRoutine(id).then(r=>{if(r){setName(r.name);setItems(r.exercises.map(e=>({exercise:e.exercise!,setCount:e.setCount})))}})},[id]);
  const move=(index:number,direction:number)=>{const next=[...items];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setItems(next)};
  const save=async()=>{if(!name.trim())return Alert.alert('Name your routine');if(!items.length)return Alert.alert('Add at least one exercise');await saveRoutine({id:id==='new'?undefined:id,name,exercises:items.map(v=>({exerciseId:v.exercise.id,setCount:v.setCount}))});refresh();router.back()};
  return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={[styles.cancel,{color:t.secondary}]}>Cancel</Text></Pressable><Text style={[styles.headerTitle,{color:t.text}]}>{id==='new'?'New routine':'Edit routine'}</Text><Pressable onPress={save}><Text style={[styles.save,{color:t.accentDark}]}>Save</Text></Pressable></View><TextInput value={name} onChangeText={setName} placeholder="Routine name" placeholderTextColor={t.secondary} style={[styles.name,{color:t.text,backgroundColor:t.input}]}/><FlatList data={items} keyExtractor={i=>i.exercise.id} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={[styles.empty,{color:t.secondary}]}>Add exercises in the order you want to perform them.</Text>} renderItem={({item,index})=><View style={[styles.item,{backgroundColor:t.surface,borderColor:t.border}]}><View style={{flex:1}}><Text style={[styles.itemName,{color:t.text}]}>{item.exercise.name}</Text><Text style={{color:t.secondary}}>{item.exercise.muscleGroup}</Text></View><View style={styles.setControl}><Pressable onPress={()=>setItems(v=>v.map((x,i)=>i===index?{...x,setCount:Math.max(1,x.setCount-1)}:x))}><Ionicons name="remove-circle-outline" size={25} color={t.secondary}/></Pressable><Text style={[styles.setText,{color:t.text}]}>{item.setCount} sets</Text><Pressable onPress={()=>setItems(v=>v.map((x,i)=>i===index?{...x,setCount:Math.min(10,x.setCount+1)}:x))}><Ionicons name="add-circle-outline" size={25} color={t.accentDark}/></Pressable></View><View style={styles.arrows}><Pressable onPress={()=>move(index,-1)}><Ionicons name="chevron-up" size={20} color={t.secondary}/></Pressable><Pressable onPress={()=>move(index,1)}><Ionicons name="chevron-down" size={20} color={t.secondary}/></Pressable></View><Pressable onPress={()=>setItems(v=>v.filter((_,i)=>i!==index))}><Ionicons name="close" size={22} color={t.danger}/></Pressable></View>} ListFooterComponent={<PrimaryButton title="Add exercise" kind="secondary" onPress={()=>setPicker(true)}/>}/><ExercisePicker visible={picker} onClose={()=>setPicker(false)} onSelect={exercise=>{setItems(v=>v.some(x=>x.exercise.id===exercise.id)?v:[...v,{exercise,setCount:3}]);setPicker(false)}}/></Screen>;
}
const styles=StyleSheet.create({header:{height:58,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerTitle:{fontSize:18,fontWeight:'800'},cancel:{fontSize:16},save:{fontSize:16,fontWeight:'800'},name:{height:54,margin:16,borderRadius:15,paddingHorizontal:16,fontSize:19,fontWeight:'700'},list:{paddingHorizontal:16,paddingBottom:40,gap:10,flexGrow:1},empty:{textAlign:'center',padding:36,lineHeight:22},item:{borderWidth:1,borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',gap:10},itemName:{fontSize:16,fontWeight:'700',marginBottom:3},setControl:{alignItems:'center',gap:2},setText:{fontSize:12,fontWeight:'700'},arrows:{gap:1}});
